language: generic

sudo: required

services:
  - docker

before_install: 
  - docker build -t nicolaslazzos/client-test -f ./client/Dockerfile.dev ./client
  # we could add more builds like that to test the other services like the server and the worker

script:
  - docker run -e CI=true nicolaslazzos/client-test npm run test:ci
  # same here

after_success:
  - docker build -t nicolaslazzos/multiple-docker-client ./client
  - docker build -t nicolaslazzos/multiple-docker-server ./server
  - docker build -t nicolaslazzos/multiple-docker-worker ./worker
  - docker build -t nicolaslazzos/multiple-docker-nginx ./nginx

  # push images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push nicolaslazzos/multiple-docker-client
  - docker push nicolaslazzos/multiple-docker-server
  - docker push nicolaslazzos/multiple-docker-worker
  - docker push nicolaslazzos/multiple-docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multiple-docker-ci-cd"
  env: "Multipledockercicd-env"
  bucket_name: "elasticbeanstalk-us-east-1-161028048438"
  bucket_path: "multiple-docker-ci-cd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY