version: '3'
services:
  nginx:
    hostname: nginx
    image: nicolaslazzos/multiple-docker-nginx
    restart: always
    mem_limit: 128m
    ports:
      - "80:80"
    depends_on:
      - api
      - client
  api:
    hostname: api
    image: nicolaslazzos/multiple-docker-server
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PG_USER
      - PG_HOST=$PG_HOST
      - PG_DATABASE=$PG_DATABASE
      - PG_PASSWORD=$PG_PASSWORD
      - PG_PORT=PG_PORT
  client:
    hostname: client
    image: nicolaslazzos/multiple-docker-client
    mem_limit: 128m
  worker:
    hostname: worker
    image: nicolaslazzos/multiple-docker-worker
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
